### PR TITLE
Pin git srcrevs

### PR DESCRIPTION
**Pull request by bengardiner-at-irdeto**
This PR depends on pull request #20.

In issue #19 I noticed that it's not possible to reproduce historical builds because all the ```ccsp-*``` recipes use ```${AUTOREV}``` for their ```SRCREV```s

These changes (8d1d591 and c593572 are the new commits relative to PR #20)
* specify the SRCREVs of the recipes explicitly as SHA1s on ```${CCSP_GIT_BRANCH}```
* adds ```conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` which can be included in local.conf to set all ```SRCREV```s to ```${AUTOREV}``` -- this is patterned after the yocto practice of ```conf/distro/include/poky-floating-revisions.inc```. Please see section 5.14 of the yocto 1.6 user manual for more details http://www.yoctoproject.org/docs/1.6/dev-manual/dev-manual.html.

With these changes merged, historical builds of this layer will be reproducible since they will refer to specific commits in the ```ccsp-*``` recipes. For ease of testing new revisions in those external git repos, it should be sufficient to add  ```require conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` to your local.conf

I tested these changes by first confirming the fetch of the correct SHA1 for each ```ccsp-*``` recipe without ```require conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` in my local.conf. Then again with ```require conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` in my local.conf Then I tested a failure to fetch each recipe with an invalid SHA1 (deadbeefdeadbeefdeadbeefdeadbeefdeadbeef) in place of each ```SRCREV_pn-<PN>``` in ```conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` in turn -- to confirm that the values in that ```.inc``` file were propagating into the recipe's apparent ```SRCREV```.

### CODE REVIEW

**Comment by s-maynard** [comment]
changing SRCREV to explicit and removing the 'name=' in the SRCURIs will break a certain company's build.  The changes from the previous pull request look good (building now)...

**Comment by bengardiner-at-irdeto** [comment]
Would it be possible for this company to update their local.conf to ```require conf/distro/include/meta-rdk-belvedere-floating-revisions.inc``` ?

**Comment by s-maynard** [comment]
I'm no longer on their team - but I will ping them...
In the meantime the other pull request is fine and I'll merge it in.

**Comment by bengardiner-at-irdeto** [comment]
That's cool. Thanks, Steve! :)

Glad the other PR helped

**Comment by s-maynard** [comment]
ok - so the name parameter is used to allow switching repo locations (legacy versus new)
sounds like your change depends on the removal of name...

**Comment by bengardiner-at-irdeto** [comment]
Yeah -- I haven't figured a way to get meta-rdk-belvedere-floating-revisions.inc to override SRCREV when the name= parameter is used. OK, so that's a blocker. I'll try to figure out a way to get this working without removing name=

**Comment by bengardiner-at-irdeto** [comment]
I figured out how to keep the name= parameters in SRC_URI and still make floating_revisions.inc work.

**Pull request merged**
